server:
  port: 9086

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8085/

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddlAuto: none

  sql:
    init:
      mode: always

