server:
  port: 8084

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:9001/eureka

spring:
  main:
    web:

  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/api/v1/product/**
          filters:
            - AuthenticationFilter
#  Before routing to service, apply above filter

        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/api/v1/orderService/**
          filters:
            - AuthenticationFilter

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
          - Path=/api/v1/productInventory/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
          - Path=/auth/**

  config:
    import: optional:configserver:http://localhost:8085

