server:
  port: 8082

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411/

  jpa:
    defer-datasource-initialization: true
    generateDdl: true
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_mngmnt?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345



  config:
    import: optional:configserver:http://localhost:8085

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      showDetails: always

resilience4j:
  circuitbreaker:
    instances:
      inventoryServiceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState : 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED