server:
  port: 8081

spring:
  application:
    name: product-service
#  profiles:
#    active: dev


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddlAuto: none

  sql:
    init:
      mode: always

  config:
    import: optional:configserver:http://localhost:8085


