server:
  port: 8083

spring:
  application:
    name: inventory-service
  zipkin:
    base-url: http://localhost:9411/
  #  profiles:
  #    active: dev


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddlAuto: none

  sql:
    init:
      mode: always

  config:
    import: optional:configserver:http://localhost:8085


